<template><h1 id="流程控制" tabindex="-1"><a class="header-anchor" href="#流程控制" aria-hidden="true">#</a> 流程控制</h1>
<p>所有的算法都是通过顺序、分支、循环这三种逻辑实现的</p>
<ul>
<li><strong>顺序</strong> --从 <strong>a</strong> 到 <strong>b</strong></li>
<li><strong>分支</strong> --根据条件<strong>选择性</strong>的执行</li>
<li><strong>循环</strong> --<strong>重复不断</strong>的执行</li>
</ul>
<h2 id="分支结构" tabindex="-1"><a class="header-anchor" href="#分支结构" aria-hidden="true">#</a> 分支结构</h2>
<h3 id="if" tabindex="-1"><a class="header-anchor" href="#if" aria-hidden="true">#</a> IF</h3>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF">(exp)</span><span style="color: #89DDFF">{</span><span style="color: #EEFFFF">代码块</span><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre></div><p>当(exp)的布尔值结果为true的时候，执行{代码块}，否则不执行</p>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF">(exp)</span><span style="color: #89DDFF">{</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">代码块1</span><span style="color: #F07178"> </span><span style="color: #89DDFF">}</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">代码块2</span><span style="color: #F07178"> </span><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre></div><p>当(exp)的布尔值结果为true的时候，执行{代码块1}，否则执行{代码块2}</p>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #EEFFFF">exp1 </span><span style="color: #89DDFF">?</span><span style="color: #EEFFFF"> exp2 </span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> exp3 </span></span>
<span class="line"></span></code></pre></div><p>如果exp1的结果是true 运行exp2，否则运行exp3</p>
<div class="custom-container tip"><p class="custom-container-title">提示</p>
<p><strong><code v-pre>if(exp){代码块}</code></strong> 的写法，可以将 <strong><code v-pre>花括号</code></strong> <strong><code v-pre>{ }</code></strong> 省略掉，但会使可读性变差，且存在代隐患。</p>
</div>
<hr>
<p><strong>if(exp){代码块}</strong> <Badge text="DEMO" /></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 小艺粥坊 : 如果满30减15</span></span>
<span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> money </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">35</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF"> (money </span><span style="color: #89DDFF">&gt;=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">30</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">money</span><span style="color: #F07178"> </span><span style="color: #89DDFF">-=</span><span style="color: #F07178"> </span><span style="color: #F78C6C">15</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">实际付款:</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> money)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #545454; font-style: italic">// 实际付款：20</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><hr>
<p><strong>促销活动</strong> <Badge text="练习" /><br>
小艺航空公司机票促销，如果是春季机票8折，原价2000，如果申哥现在买机票应该花多少钱?</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 声明2个变量存储价格和月份 完成判断 </span></span>
<span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> price </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">2000</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> month </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">3</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF"> (month </span><span style="color: #89DDFF">==</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">3</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">||</span><span style="color: #EEFFFF"> month </span><span style="color: #89DDFF">==</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">4</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">||</span><span style="color: #EEFFFF"> month </span><span style="color: #89DDFF">==</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">5</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">price</span><span style="color: #F07178"> </span><span style="color: #89DDFF">*=</span><span style="color: #F07178"> </span><span style="color: #F78C6C">0.8</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">实付款:</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> price)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #545454; font-style: italic">// 实付款:1600</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><hr>
<p><strong>交换变量的值</strong> <Badge text="练习" /><br>
假设有2个变量a，b，如果a大于b，则交换2个变量的值 ，只可以借助1个第三方变量</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 例如: a = 2  b = 1  交换值 a = 1 b = 2 </span></span>
<span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> a </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">2</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> b </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> tmp</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF"> (a </span><span style="color: #89DDFF">&gt;</span><span style="color: #EEFFFF"> b) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">tmp</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">a</span><span style="color: #89DDFF">;</span><span style="color: #F07178">    </span><span style="color: #545454; font-style: italic">// 把较大的a变量的值给tmp</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">a</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">b</span><span style="color: #89DDFF">;</span><span style="color: #F07178">      </span><span style="color: #545454; font-style: italic">// 把较小的b变量的值给a</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">b</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">tmp</span><span style="color: #89DDFF">;</span><span style="color: #F07178">    </span><span style="color: #545454; font-style: italic">// 把tmp的值给b</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><hr>
<p><strong>满减</strong> <Badge text="练习" /><br>
如果满30减15， 如果不够30 则提示还差xx元可以减15元</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> mon </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">20</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF"> </span><span style="color: #545454; font-style: italic">// 声明一个变量为实际付款值</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF"> (mon </span><span style="color: #89DDFF">&gt;=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">30</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">mon</span><span style="color: #F07178"> </span><span style="color: #89DDFF">-=</span><span style="color: #F07178"> </span><span style="color: #F78C6C">15</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">还差:</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178"> </span><span style="color: #89DDFF">+</span><span style="color: #F07178"> (</span><span style="color: #F78C6C">30</span><span style="color: #F07178"> </span><span style="color: #89DDFF">-</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">mon</span><span style="color: #F07178">) </span><span style="color: #89DDFF">+</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">元可以减15元</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">实付款:</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> mon)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><hr>
<p>判断奇偶数 <Badge text="练习" /><br>
声明变量保存一个数字判断是奇数还是偶数，分别做输出</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> num </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">5</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #545454; font-style: italic">// 第一种</span></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF"> (num </span><span style="color: #89DDFF">%</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">2</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">==</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">0</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">偶数</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">奇数</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #545454; font-style: italic">// 第二种</span></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF"> (num </span><span style="color: #89DDFF">%</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">2</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">!=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">0</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">奇数</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">偶数</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #545454; font-style: italic">// 第三种</span></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF"> (num</span><span style="color: #89DDFF">%</span><span style="color: #F78C6C">2</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">num</span><span style="color: #89DDFF">,</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">奇数</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">num</span><span style="color: #89DDFF">,</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">偶数</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #545454; font-style: italic">// 第四种 三元(三目)运算符</span></span>
<span class="line"><span style="color: #EEFFFF">num </span><span style="color: #89DDFF">%</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">2</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">==</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">0</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">?</span><span style="color: #EEFFFF"> console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">偶数</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">奇数</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br></div></div><hr>
<h3 id="if-嵌套" tabindex="-1"><a class="header-anchor" href="#if-嵌套" aria-hidden="true">#</a> IF 嵌套</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF">(exp)</span><span style="color: #89DDFF">{</span><span style="color: #EEFFFF">代码块1</span><span style="color: #89DDFF">}</span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF">(exp2)</span><span style="color: #89DDFF">{</span><span style="color: #EEFFFF">代码块2</span><span style="color: #89DDFF">}...{...}</span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #89DDFF">{</span><span style="color: #EEFFFF">语句块n</span><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><p><strong>订单状态</strong> <Badge text="演示" /></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 1 未付款  2 未发货  3运输中  其他 状态非法</span></span>
<span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> sta </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">2</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF"> (sta </span><span style="color: #89DDFF">==</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">1</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">未付款</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF"> (sta </span><span style="color: #89DDFF">==</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">2</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">未发货</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #EEFFFF"> (sta </span><span style="color: #89DDFF">==</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">3</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">运输中</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">状态非法</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><h3 id="switch-case" tabindex="-1"><a class="header-anchor" href="#switch-case" aria-hidden="true">#</a> switch case</h3>
<p>判断一个表达式的值是否和case匹配，并执行相关联的语句，如果与case的值都不匹配，执行default内容</p>
<p><strong>订单状态</strong> <Badge text="演示" /></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 1 未付款  2 未发货  3运输中  其他 状态非法</span></span>
<span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> sta </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">2</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">switch</span><span style="color: #EEFFFF"> (sta) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #89DDFF; font-style: italic">case</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">:</span></span>
<span class="line"><span style="color: #EEFFFF">        console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">未付款</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #EEFFFF">        </span><span style="color: #89DDFF; font-style: italic">break</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #89DDFF; font-style: italic">case</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">2</span><span style="color: #89DDFF">:</span></span>
<span class="line"><span style="color: #EEFFFF">        console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">未发货</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #EEFFFF">        </span><span style="color: #89DDFF; font-style: italic">break</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #89DDFF; font-style: italic">case</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">3</span><span style="color: #89DDFF">:</span></span>
<span class="line"><span style="color: #EEFFFF">        console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">运输中</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #89DDFF; font-style: italic">default</span><span style="color: #89DDFF">:</span></span>
<span class="line"><span style="color: #EEFFFF">        console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">状态非法</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #EEFFFF">        </span><span style="color: #89DDFF; font-style: italic">break</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div><h2 id="循环结构" tabindex="-1"><a class="header-anchor" href="#循环结构" aria-hidden="true">#</a> 循环结构</h2>
<p>在表达式为true的前提下，循环执行一段代码块，一直到表达式为false时结束</p>
<h3 id="while" tabindex="-1"><a class="header-anchor" href="#while" aria-hidden="true">#</a> while</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF; font-style: italic">while</span><span style="color: #EEFFFF">(exp)</span><span style="color: #89DDFF">{</span><span style="color: #EEFFFF">循环体</span><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>如果(exp)为<strong>true</strong>，执行循环体，一直到表达式为false时结束循环<br>
如果(exp)一直是<strong>true</strong>，就会造成死循环，所以while循环体中需要有<strong>增量配合</strong>(exp)</p>
<p><strong>循环体</strong> <Badge text="演示" /></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> i </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">while</span><span style="color: #EEFFFF"> (i </span><span style="color: #89DDFF">&lt;</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">5</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">小艺: Are you think of me ?</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">i</span><span style="color: #89DDFF">++;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><p>解析↑：</p>
<table>
<thead>
<tr>
<th style="text-align:center">循环次数</th>
<th style="text-align:center">i的值</th>
<th style="text-align:center">exp(i &lt; 5)</th>
<th style="text-align:center">是否执行循环体</th>
<th style="text-align:center">i++</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center">1</td>
<td style="text-align:center">1</td>
<td style="text-align:center">T</td>
<td style="text-align:center">是</td>
<td style="text-align:center">2</td>
</tr>
<tr>
<td style="text-align:center">2</td>
<td style="text-align:center">2</td>
<td style="text-align:center">T</td>
<td style="text-align:center">是</td>
<td style="text-align:center">3</td>
</tr>
<tr>
<td style="text-align:center">3</td>
<td style="text-align:center">3</td>
<td style="text-align:center">T</td>
<td style="text-align:center">是</td>
<td style="text-align:center">4</td>
</tr>
<tr>
<td style="text-align:center">4</td>
<td style="text-align:center">4</td>
<td style="text-align:center">T</td>
<td style="text-align:center">是</td>
<td style="text-align:center">5</td>
</tr>
<tr>
<td style="text-align:center">5</td>
<td style="text-align:center">5</td>
<td style="text-align:center">F</td>
<td style="text-align:center">否，结束循环</td>
<td style="text-align:center">--</td>
</tr>
</tbody>
</table>
<p><strong>使用while循环计算1到100的和</strong> <Badge text="练习" /></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 友情提示 可以借助一个第三方变量 存储相加后的值</span></span>
<span class="line"><span style="color: #545454; font-style: italic">// 1 + 2 + 3 + 4 + 5 + 6 + ... + 100</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> i </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> sum </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">0</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">while</span><span style="color: #EEFFFF"> (i </span><span style="color: #89DDFF">&lt;=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">100</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">sum</span><span style="color: #F07178"> </span><span style="color: #89DDFF">+=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">i</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">i</span><span style="color: #89DDFF">++;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(sum)</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF"> </span><span style="color: #545454; font-style: italic">// 5050 </span></span>
<span class="line"><span style="color: #545454; font-style: italic">// i = 1  sum : 0+1 = 1</span></span>
<span class="line"><span style="color: #545454; font-style: italic">// i = 2  sum : 1+2 = 3</span></span>
<span class="line"><span style="color: #545454; font-style: italic">// i = 3  sum : 3+3 = 6</span></span>
<span class="line"><span style="color: #545454; font-style: italic">// i = 4  sum : 6+4 = 10</span></span>
<span class="line"><span style="color: #545454; font-style: italic">// ...</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div><h3 id="do-while" tabindex="-1"><a class="header-anchor" href="#do-while" aria-hidden="true">#</a> do{}while()</h3>
<p>无论条件是否满足都会被无条件的执行一次循环体</p>
<Badge text="演示" />
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> i </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">0</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">do</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">小艺</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF; font-style: italic">while</span><span style="color: #EEFFFF"> (i </span><span style="color: #89DDFF">&gt;</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">5</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h3 id="for" tabindex="-1"><a class="header-anchor" href="#for" aria-hidden="true">#</a> for</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #EEFFFF">(exp1</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF">exp2</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF">exp3)</span><span style="color: #89DDFF">{</span><span style="color: #EEFFFF">循环体</span><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h4 id="for循环过程" tabindex="-1"><a class="header-anchor" href="#for循环过程" aria-hidden="true">#</a> for循环过程</h4>
<ol>
<li>先会无条件的执行<code v-pre>exp1</code>，再执行<code v-pre>exp2</code>，如果满足条件(true)才执行循环体，否则终止循环</li>
<li>当循环体执行完毕后，会执行<code v-pre>exp3</code>，进行增量操作，继续执行<code v-pre>exp2</code> 判断是否满足条件，如果满足(true)则继续执行循环体，如果不满足条件则终止循环</li>
</ol>
<p><strong>for循环</strong> <Badge text="演示" /></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #EEFFFF"> (</span><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> i </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF"> i </span><span style="color: #89DDFF">&lt;</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">5</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF"> i</span><span style="color: #89DDFF">++</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">我要回家~</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h4 id="for循环特殊写法" tabindex="-1"><a class="header-anchor" href="#for循环特殊写法" aria-hidden="true">#</a> for循环特殊写法</h4>
<p><strong>for( ; ; ){ }</strong><br>
三个表达式为空(死循环)，必须写分号(语法)<br>
需要有 <strong><code v-pre>break</code></strong> 来终止循环进行<br>
没有exp3，内部需要有相对应的增量代码</p>
<h5 id="break-终止循环-跳出循环体" tabindex="-1"><a class="header-anchor" href="#break-终止循环-跳出循环体" aria-hidden="true">#</a> break 终止循环(跳出循环体)</h5>
<p><strong>for特殊写法</strong> <Badge text="演示" /></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #EEFFFF"> (</span><span style="color: #89DDFF">;;</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">小艺</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 跳出循环体 终止循环作用</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF; font-style: italic">break</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 正常</span></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #EEFFFF"> (</span><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> i </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF"> i </span><span style="color: #89DDFF">&lt;=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">2</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF"> i</span><span style="color: #89DDFF">++</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">xiaoyi</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #545454; font-style: italic">// 第三个表达式不写，但是还想让for循环执行结果和上方for循环一样</span></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #EEFFFF"> (</span><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> i </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF"> i </span><span style="color: #89DDFF">&lt;=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">2</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">小艺</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 增量</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">i</span><span style="color: #89DDFF">++;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h4 id="for循环嵌套" tabindex="-1"><a class="header-anchor" href="#for循环嵌套" aria-hidden="true">#</a> for循环嵌套</h4>
<p>一个for循环中的循环体又是一个for循环(套娃)</p>
<h5 id="执行过程" tabindex="-1"><a class="header-anchor" href="#执行过程" aria-hidden="true">#</a> 执行过程</h5>
<ol>
<li>
<p>先执行<code v-pre>外层循环</code>， 外层循环先执行<code v-pre>exp1</code>，再执行<code v-pre>exp2</code>，如果为<code v-pre>false</code>则终止整个循环，如果为<code v-pre>true</code>则进入<code v-pre>内层循环</code>，<code v-pre>内层循环</code>也需要按照规则执行<code v-pre>exp1</code>--&gt;<code v-pre>exp2</code>--&gt;<code v-pre>循环体</code>--&gt;<code v-pre>exp3</code> ...`</p>
</li>
<li>
<p>一旦从<code v-pre>外层循环</code>进入<code v-pre>内层循环</code>后，只有等<code v-pre>内层循环</code>结束后，才会跳出<code v-pre>内层循环</code>，进入<code v-pre>外层循环</code>中</p>
</li>
<li>
<p><code v-pre>外层循环</code>每进入1次，<code v-pre>内层循环</code>都会从头开始执行n次(具体执行多少次看内层循环的条件)</p>
</li>
<li>
<p>以此类推，一直到<code v-pre>外层循环</code>条件为<code v-pre>false</code>时才会<code v-pre>终止整个循环</code></p>
</li>
</ol>
<h5 id="控制方法" tabindex="-1"><a class="header-anchor" href="#控制方法" aria-hidden="true">#</a> 控制方法</h5>
<p>外层控制行，内层控制列，先有行再有列</p>
<p><strong>绘制等腰三角形</strong> <Badge text="练习" /></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> row </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">7</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #545454; font-style: italic">//外层 for() 控制行数， 在exp1里确定r变量为行数，起始值为1</span></span>
<span class="line"><span style="color: #545454; font-style: italic">//外层 exp2明确行数关系，r&lt;=row，exp3明确变量r的自增属性</span></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #EEFFFF"> (</span><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> r </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> str </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">&#39;&#39;</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF"> r </span><span style="color: #89DDFF">&lt;=</span><span style="color: #EEFFFF"> row</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF"> r</span><span style="color: #89DDFF">++</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">  </span><span style="color: #545454; font-style: italic">//内层 for() 1控制该行里有多少个空格,变量c1确定了空格的起始数</span></span>
<span class="line"><span style="color: #89DDFF">  </span><span style="color: #545454; font-style: italic">//通过exp2明确空格和行数的关系,即空格数量应等于总输出行数减去当前行数</span></span>
<span class="line"><span style="color: #89DDFF">  </span><span style="color: #545454; font-style: italic">//通过exp3明确自增属性</span></span>
<span class="line"><span style="color: #89DDFF">  </span><span style="color: #545454; font-style: italic">//在循环体中,给变量拼接 &#39;空格&#39;</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #F07178"> (</span><span style="color: #C792EA">var</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">c1</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">c1</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&lt;=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">row</span><span style="color: #F07178"> </span><span style="color: #89DDFF">-</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">r</span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">c1</span><span style="color: #89DDFF">++</span><span style="color: #F07178">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">str</span><span style="color: #F07178"> </span><span style="color: #89DDFF">+=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #89DDFF">  </span><span style="color: #545454; font-style: italic">//内层 for() 2控制该行里有多少个星,变量c1确定了星的起始数</span></span>
<span class="line"><span style="color: #89DDFF">  </span><span style="color: #545454; font-style: italic">//通过exp2明确星和行数的关系,即星的数量=行数x2-1</span></span>
<span class="line"><span style="color: #89DDFF">  </span><span style="color: #545454; font-style: italic">//通过exp3明确自增属性</span></span>
<span class="line"><span style="color: #89DDFF">  </span><span style="color: #545454; font-style: italic">//在循环体中,给变量拼接 &#39;*&#39;</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #F07178"> (</span><span style="color: #C792EA">var</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">c</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">c</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&lt;=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">r</span><span style="color: #F07178"> </span><span style="color: #89DDFF">*</span><span style="color: #F07178"> </span><span style="color: #F78C6C">2</span><span style="color: #F07178"> </span><span style="color: #89DDFF">-</span><span style="color: #F07178"> </span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">c</span><span style="color: #89DDFF">++</span><span style="color: #F07178">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">str</span><span style="color: #F07178"> </span><span style="color: #89DDFF">+=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">*</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #EEFFFF">str</span><span style="color: #F07178"> </span><span style="color: #89DDFF">+=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">\n</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(str)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br></div></div><p><strong>绘制倒置等腰三角形</strong> <Badge text="练习" /></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> gndrow </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">7</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #EEFFFF"> (</span><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> sr </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> gndrow </span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF">str </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">&#39;&#39;</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF"> sr </span><span style="color: #89DDFF">&gt;=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">0</span><span style="color: #89DDFF">;</span><span style="color: #EEFFFF"> sr</span><span style="color: #89DDFF">--</span><span style="color: #EEFFFF">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #545454; font-style: italic">// 输出的空格数量等与总行数-当前行数</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #F07178">(</span><span style="color: #C792EA">var</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">sc</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #F78C6C">0</span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">sc</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&lt;=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">gndrow</span><span style="color: #89DDFF">-</span><span style="color: #EEFFFF">sr</span><span style="color: #F07178"> </span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">sc</span><span style="color: #89DDFF">++</span><span style="color: #F07178">)</span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">str</span><span style="color: #89DDFF">+=</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #545454; font-style: italic">// 输出星的数量等与当前行数的两倍减1,输出自减</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #F07178"> (</span><span style="color: #C792EA">var</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">sc1</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #F78C6C">2</span><span style="color: #89DDFF">*</span><span style="color: #EEFFFF">sr</span><span style="color: #89DDFF">-</span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">sc1</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&gt;</span><span style="color: #F78C6C">0</span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">sc1</span><span style="color: #89DDFF">--</span><span style="color: #F07178">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">str</span><span style="color: #89DDFF">+=</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">*</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">str</span><span style="color: #89DDFF">+=</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">\n</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(sstr)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div></template>
