<template><h1 id="mysql模块" tabindex="-1"><a class="header-anchor" href="#mysql模块" aria-hidden="true">#</a> Mysql模块</h1>
<p>在Node.js下操作mysql数据库的模块。</p>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #EEFFFF">npm i mysql</span></span>
<span class="line"></span></code></pre></div><div class="custom-container tip"><p class="custom-container-title">提示</p>
<p>关于数据库的操作，可以参考：
<RouterLink to="/Code/DATA/">MySql</RouterLink></p>
</div>
<h2 id="连接池" tabindex="-1"><a class="header-anchor" href="#连接池" aria-hidden="true">#</a> 连接池</h2>
<p>Mysql连接池是一种池化技术，池化技术指的是提前准备一些资源，在需要时可以重复使用这些预先准备的资源。<br>
建立Mysql连接池</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #C792EA">let</span><span style="color: #EEFFFF"> pool </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> mysql</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">createPool</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">host</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">127.0.0.1</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF">    </span><span style="color: #545454; font-style: italic">// 主机地址</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">port</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">3306</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF">    </span><span style="color: #545454; font-style: italic">// 端口号</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">user</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">root</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF">    </span><span style="color: #545454; font-style: italic">// 用户名</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">password</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">&#39;&#39;</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF">    </span><span style="color: #545454; font-style: italic">// 密码</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">database</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">prd</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF">    </span><span style="color: #545454; font-style: italic">// 数据库</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">connectionLimit</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">15</span><span style="color: #EEFFFF">    </span><span style="color: #545454; font-style: italic">// 连接池数量</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><h2 id="操作-含建立流程" tabindex="-1"><a class="header-anchor" href="#操作-含建立流程" aria-hidden="true">#</a> 操作（含建立流程）</h2>
<p>即数据库的增删改查，代码参考：</p>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #EEFFFF">pool</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">query</span><span style="color: #EEFFFF">(sql</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF">[数据信息]</span><span style="color: #89DDFF">,(</span><span style="color: #EEFFFF">err</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF">result</span><span style="color: #89DDFF">)</span><span style="color: #C792EA">=&gt;</span><span style="color: #89DDFF">{</span><span style="color: #F07178"> </span><span style="color: #89DDFF">}</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre></div><ul>
<li><strong><code v-pre>增</code></strong> <strong><code v-pre>删</code></strong> <strong><code v-pre>改</code></strong> 返回的是数据表中<code v-pre>受影响的行数</code>，可以通过<code v-pre>result.affectRows</code>，对结果进行判断。</li>
<li><strong><code v-pre>查</code></strong> 返回的是<code v-pre>数组</code>，可以通过<code v-pre>result.length</code>，对结果进行判断。
<ul>
<li>如果没有查询到，返回的是<code v-pre>空数组</code>，因此<code v-pre>result.length = 0</code></li>
</ul>
</li>
</ul>
<p><strong><code v-pre>DEMO</code></strong> Mysql模块操作 增删改查</p>
<h3 id="_1-建立express服务器" tabindex="-1"><a class="header-anchor" href="#_1-建立express服务器" aria-hidden="true">#</a> 1. 建立express服务器</h3>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #C792EA">const</span><span style="color: #EEFFFF"> express </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">require</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">express</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #C792EA">const</span><span style="color: #EEFFFF"> app </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">express</span><span style="color: #EEFFFF">()</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #C792EA">const</span><span style="color: #EEFFFF"> port </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">8080</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #EEFFFF">app</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">listen</span><span style="color: #EEFFFF">(port</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #EEFFFF"> console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">服务器已经启动,监听的端口是:</span><span style="color: #89DDFF">${</span><span style="color: #EEFFFF">port</span><span style="color: #89DDFF">}</span><span style="color: #C3E88D">!</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF">))</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre></div><h3 id="_2-托管静态资源" tabindex="-1"><a class="header-anchor" href="#_2-托管静态资源" aria-hidden="true">#</a> 2. 托管静态资源</h3>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #EEFFFF">app</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">use</span><span style="color: #EEFFFF">(express</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">static</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">public</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">))</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #EEFFFF">app</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">use</span><span style="color: #EEFFFF">(express</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">urlencoded</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">extended</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #FF9CAC">false</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF">))</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre></div><div class="custom-container tip"><p class="custom-container-title">提示</p>
<p><code v-pre>express.urlencoded</code> 是用于解析 <code v-pre>URL-encoded</code> 格式请求体数据的。</p>
<ul>
<li><code v-pre>extended</code>设置为<code v-pre>false</code>，对<code v-pre>URL-encoded</code>的数据的解析采用<code v-pre>querystring</code>库；</li>
<li><code v-pre>extended</code>设置为<code v-pre>true</code>，采用<code v-pre>querystring</code>库，并允许将富对象和数组编码为url编码格式，允许使用url编码的json体验。</li>
</ul>
<p><strong><code v-pre>DEMO</code></strong>
当<code v-pre>extended</code>为<code v-pre>false</code>时,键值对中的值就为'String'或'Array'形式，<br>
<code v-pre>bodyParser.urlencoded({extended:false})</code>的结果为</p>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">movie[_id]</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">undefined</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">movie[title]</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">机械战警</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">movie[img]</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">(https://r3.ykimg.com/05160000530EEB63675839160D0B79D5)</span><span style="color: #89DDFF">&#39;</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre></div><p>当<code v-pre>extended</code>为<code v-pre>true</code>时,则可为任何数据类型，<br>
<code v-pre>bodyParser.urlencoded({extended:true})</code>的结果为</p>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #FFCB6B">movie</span><span style="color: #89DDFF">:{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #FFCB6B">_id</span><span style="color: #89DDFF">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">undefined</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #FFCB6B">title</span><span style="color: #89DDFF">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">机械战警</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #FFCB6B">img</span><span style="color: #89DDFF">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">(https://r3.ykimg.com/05160000530EEB63675839160D0B79D5)</span><span style="color: #89DDFF">&#39;</span></span>
<span class="line"><span style="color: #F07178">  </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #89DDFF">}</span></span>
<span class="line"></span></code></pre></div></div>
<h3 id="_3-引入mysql模块" tabindex="-1"><a class="header-anchor" href="#_3-引入mysql模块" aria-hidden="true">#</a> 3. 引入mysql模块</h3>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #C792EA">const</span><span style="color: #EEFFFF"> mysql </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">require</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">mysql</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #545454; font-style: italic">// 创建mysql连接池的操作(固定写法)</span></span>
<span class="line"><span style="color: #545454; font-style: italic">// mysql.createConnection</span></span>
<span class="line"><span style="color: #C792EA">let</span><span style="color: #EEFFFF"> pool </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> mysql</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">createPool</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 主机地址</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">host</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">127.0.0.1</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 端口号</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">port</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">3306</span><span style="color: #89DDFF">,</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 用户名</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">user</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">root</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 密码</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">password</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">&#39;&#39;</span><span style="color: #89DDFF">,</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 数据库</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">database</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">prd</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 连接池数量</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #F07178">connectionLimit</span><span style="color: #89DDFF">:</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">15</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre></div><h4 id="配套数据" tabindex="-1"><a class="header-anchor" href="#配套数据" aria-hidden="true">#</a> 配套数据</h4>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #F78C6C">SET</span><span style="color: #EEFFFF"> NAMES UTF8;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F78C6C">DROP</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">DATABASE</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">IF</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">EXISTS</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">prd</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF">;</span></span>
<span class="line"><span style="color: #F78C6C">CREATE</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">DATABASE</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">prd</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF"> </span><span style="color: #C792EA">DEFAULT</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">CHARACTER</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">SET</span><span style="color: #EEFFFF"> UTF8;</span></span>
<span class="line"><span style="color: #F78C6C">USE</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">prd</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #545454; font-style: italic">-- 创建商品表</span></span>
<span class="line"><span style="color: #F78C6C">CREATE</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">TABLE</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">product</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF">(</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">id</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">INT</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">KEY</span><span style="color: #EEFFFF"> AUTO_INCREMENT,</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">pname</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">VARCHAR</span><span style="color: #EEFFFF">(</span><span style="color: #F78C6C">40</span><span style="color: #EEFFFF">),</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">title</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">VARCHAR</span><span style="color: #EEFFFF">(</span><span style="color: #F78C6C">40</span><span style="color: #EEFFFF">),</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">price</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">VARCHAR</span><span style="color: #EEFFFF">(</span><span style="color: #F78C6C">40</span><span style="color: #EEFFFF">)</span></span>
<span class="line"><span style="color: #EEFFFF">)</span><span style="color: #C792EA">DEFAULT</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">CHARACTER</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">SET</span><span style="color: #EEFFFF"> UTF8;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F78C6C">INSERT</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">INTO</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">product</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">VALUES</span><span style="color: #EEFFFF">(</span><span style="color: #F78C6C">NULL</span><span style="color: #EEFFFF">,</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">三星W2022</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">,</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">三星 SAMSUNG 心系天下W22 5G 折叠屏 骁龙888 5G手机 16＋512GB雅瓷黑</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">,</span><span style="color: #F78C6C">23999</span><span style="color: #EEFFFF">);</span></span>
<span class="line"><span style="color: #F78C6C">INSERT</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">INTO</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">product</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">VALUES</span><span style="color: #EEFFFF">(</span><span style="color: #F78C6C">NULL</span><span style="color: #EEFFFF">,</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">小米11</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">,</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">小米11 5G 骁龙888 2K AMOLED四曲面柔性屏 游戏手机 8G+128GB 白色</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">,</span><span style="color: #F78C6C">3799</span><span style="color: #EEFFFF">);</span></span>
<span class="line"><span style="color: #F78C6C">INSERT</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">INTO</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">product</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">VALUES</span><span style="color: #EEFFFF">(</span><span style="color: #F78C6C">NULL</span><span style="color: #EEFFFF">,</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">vivo</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">,</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">vivo X60 5G手机 5nm旗舰芯片蔡司光学镜头vivox60手机 微光 8GB+256GB</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">,</span><span style="color: #F78C6C">2799</span><span style="color: #EEFFFF">);</span></span>
<span class="line"><span style="color: #F78C6C">INSERT</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">INTO</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">product</span><span style="color: #89DDFF">`</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">VALUES</span><span style="color: #EEFFFF">(</span><span style="color: #F78C6C">NULL</span><span style="color: #EEFFFF">,</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">华为</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">,</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">华为 Mate40 5G 手机【支持鸿蒙HarmonyOs】 亮黑色 mate40E(8+128G)</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">,</span><span style="color: #F78C6C">4959</span><span style="color: #EEFFFF">);</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br></div></div><h3 id="查" tabindex="-1"><a class="header-anchor" href="#查" aria-hidden="true">#</a> 查</h3>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 1. 查询所有的商品信息 get /list</span></span>
<span class="line"><span style="color: #EEFFFF">app</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">get</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">/list</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">(</span><span style="color: #EEFFFF">req</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> res</span><span style="color: #89DDFF">)</span><span style="color: #EEFFFF"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 执行sql查询所有用户信息</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">sql</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">SELECT * FROM product</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">pool</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">query</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">sql</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> </span><span style="color: #89DDFF">(</span><span style="color: #EEFFFF">err</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">result</span><span style="color: #89DDFF">)</span><span style="color: #F07178"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #F07178"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #F07178"> (</span><span style="color: #EEFFFF">err</span><span style="color: #F07178">) </span><span style="color: #89DDFF; font-style: italic">throw</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">err</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 查询返回的是数组</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">res</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">send</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">result</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #545454; font-style: italic">// 2. 检索指定的商品信息 id=1 get /list/1</span></span>
<span class="line"><span style="color: #EEFFFF">app</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">get</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">/list/:id</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">(</span><span style="color: #EEFFFF">req</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> res</span><span style="color: #89DDFF">)</span><span style="color: #EEFFFF"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 获取路由传递的参数</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">obj</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">req</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">params</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">obj</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">sql</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">SELECT * FROM product WHERE id = ?</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">pool</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">query</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">sql</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> [</span><span style="color: #EEFFFF">obj</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">id</span><span style="color: #F07178">]</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> </span><span style="color: #89DDFF">(</span><span style="color: #EEFFFF">err</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">result</span><span style="color: #89DDFF">)</span><span style="color: #F07178"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #F07178"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #F07178"> (</span><span style="color: #EEFFFF">err</span><span style="color: #F07178">) </span><span style="color: #89DDFF; font-style: italic">throw</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">err</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">result</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 如果数组的长度大于0说明不是空数组</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #F07178"> (</span><span style="color: #EEFFFF">result</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">length</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&gt;</span><span style="color: #F07178"> </span><span style="color: #F78C6C">0</span><span style="color: #F07178">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #EEFFFF">res</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">send</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">result</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF">}</span><span style="color: #F07178"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #F07178"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #EEFFFF">res</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">send</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">查询的内容不存在</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre></div><h4 id="sql注入" tabindex="-1"><a class="header-anchor" href="#sql注入" aria-hidden="true">#</a> SQL注入</h4>
<p>传递参数可能会造成mysql的二义性，即传递一个参数，但是mysql当作关键字处理了。<br>
<code v-pre>SELECT * FROM product WHERE id = 1  </code></p>
<p><strong>例如</strong>: SELECT * FROM product WHERE <code v-pre>id = 1 or 1 = 1</code><br>
<code v-pre>id = 1 or 1 = 1 </code> 一个判断 1=1 就是真ture 一直则全真<br>
这样的传递不安全,假设传递的参数是恶意的: 1 or 1 = 1容易造成sql注入导致信息泄露</p>
<p>安全做法: <code v-pre>预处理 </code><br>
先试用，问号<code v-pre>?</code> 作为占位符</p>
<p><strong>防止SQL注入</strong> 使用预处理,即使用<code v-pre>?</code>作为占位符。<br>
预处理会进行参数的分析，甄别传参是否需要。<br>
let sql = <code v-pre>SELECT * FROM product WHERE id = ?</code>;</p>
<h3 id="增" tabindex="-1"><a class="header-anchor" href="#增" aria-hidden="true">#</a> 增</h3>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 3. 添加商品 </span></span>
<span class="line"><span style="color: #EEFFFF">app</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">post</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">/add</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">(</span><span style="color: #EEFFFF">req</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> res</span><span style="color: #89DDFF">)</span><span style="color: #EEFFFF"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 获取数据</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">obj</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">req</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">body</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">obj</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 执行sql</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">sql</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">INSERT INTO product SET ? </span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// mysql模块支持使用对象形式添加信息</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">pool</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">query</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">sql</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> [</span><span style="color: #EEFFFF">obj</span><span style="color: #F07178">]</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> </span><span style="color: #89DDFF">(</span><span style="color: #EEFFFF">err</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">result</span><span style="color: #89DDFF">)</span><span style="color: #F07178"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #F07178"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #F07178"> (</span><span style="color: #EEFFFF">err</span><span style="color: #F07178">) </span><span style="color: #89DDFF; font-style: italic">throw</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">err</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 插入操作返回的是受影响的行数</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// console.log(result);</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #F07178"> (</span><span style="color: #EEFFFF">result</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">affectedRows</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&gt;</span><span style="color: #F07178"> </span><span style="color: #F78C6C">0</span><span style="color: #F07178">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">            </span><span style="color: #545454; font-style: italic">// 响应结果</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #EEFFFF">res</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">send</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">添加商品成功~~</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF">}</span><span style="color: #F07178"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #F07178"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #EEFFFF">res</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">send</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">添加商品失败~~</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre></div><h3 id="改" tabindex="-1"><a class="header-anchor" href="#改" aria-hidden="true">#</a> 改</h3>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 4. 更新商品</span></span>
<span class="line"><span style="color: #EEFFFF">app</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">post</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">/update</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">(</span><span style="color: #EEFFFF">req</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> res</span><span style="color: #89DDFF">)</span><span style="color: #EEFFFF"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 获取数据信息</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">obj</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">req</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">body</span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #545454; font-style: italic">//10分钟 16:41继续</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// console.log(obj);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 执行sql</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">sql</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">UPDATE product SET ? WHERE id = ?</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">pool</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">query</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">sql</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> [</span><span style="color: #EEFFFF">obj</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">obj</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">id</span><span style="color: #F07178">]</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> </span><span style="color: #89DDFF">(</span><span style="color: #EEFFFF">err</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">result</span><span style="color: #89DDFF">)</span><span style="color: #F07178"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #F07178"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 响应内容</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #F07178"> (</span><span style="color: #EEFFFF">err</span><span style="color: #F07178">) </span><span style="color: #89DDFF; font-style: italic">throw</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">err</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// console.log(result);</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 更新操作同样返回的是受影响的行数</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #F07178"> (</span><span style="color: #EEFFFF">result</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">affectedRows</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&gt;</span><span style="color: #F07178"> </span><span style="color: #F78C6C">0</span><span style="color: #F07178">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #EEFFFF">res</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">send</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">更新商品成功~</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF">}</span><span style="color: #F07178"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #F07178"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #EEFFFF">res</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">send</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">更新商品失败~</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre></div><h3 id="删" tabindex="-1"><a class="header-anchor" href="#删" aria-hidden="true">#</a> 删</h3>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 5. 删除商品</span></span>
<span class="line"><span style="color: #EEFFFF">app</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">get</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">/delete/:id</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">(</span><span style="color: #EEFFFF">req</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF"> res</span><span style="color: #89DDFF">)</span><span style="color: #EEFFFF"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 获取数据</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">obj</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">req</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">params</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// console.log(obj);</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 执行sql</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">sql</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">DELETE FROM product WHERE id = ?</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">pool</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">query</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">sql</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> [</span><span style="color: #EEFFFF">obj</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">id</span><span style="color: #F07178">]</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> </span><span style="color: #89DDFF">(</span><span style="color: #EEFFFF">err</span><span style="color: #89DDFF">,</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">result</span><span style="color: #89DDFF">)</span><span style="color: #F07178"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #F07178"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #F07178"> (</span><span style="color: #EEFFFF">err</span><span style="color: #F07178">) </span><span style="color: #89DDFF; font-style: italic">throw</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">err</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 响应内容</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 删除操作同样返回的是受影响的行数</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #F07178"> (</span><span style="color: #EEFFFF">result</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">affectedRows</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&gt;</span><span style="color: #F07178"> </span><span style="color: #F78C6C">0</span><span style="color: #F07178">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #EEFFFF">res</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">send</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">删除成功~~~</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF">}</span><span style="color: #F07178"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #F07178"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #EEFFFF">res</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">send</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">删除失败~~~</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre></div><div class="custom-container tip"><p class="custom-container-title">格式化json数据</p>
<p>当前返回的数据基本都是json格式，默认展示样式较为粗糙、混乱，可以使用浏览器插件格式化展示样式。
比如:JSON-handle</p>
</div>
</template>
