<template><div><h2 id="定时器" tabindex="-1"><a class="header-anchor" href="#定时器" aria-hidden="true">#</a> <strong>定时器</strong> <Badge text="重点" /></h2>
<p>定时器基于事件循环，基本应用于4种场景：</p>
<ul>
<li>计时器炸弹</li>
<li>闹钟</li>
<li>秒杀倒计时</li>
<li>轮播图
......</li>
</ul>
<h3 id="一次性定时器" tabindex="-1"><a class="header-anchor" href="#一次性定时器" aria-hidden="true">#</a> 一次性定时器</h3>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #82AAFF">setTimeout</span><span style="color: #EEFFFF">(callback</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF">time</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF">[</span><span style="color: #89DDFF">...</span><span style="color: #EEFFFF">])</span></span>
<span class="line"></span></code></pre></div><p>计划在xxx毫秒后执行一次回调函数<code v-pre>callback</code>,返回一个<code v-pre>timeObject</code>,供<code v-pre>clearTimeout</code>在需要的时候使用.</p>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #82AAFF">clearTimeout</span><span style="color: #EEFFFF">(timeObject)</span></span>
<span class="line"></span></code></pre></div><p>清除一次性定时器</p>
<p><code v-pre>DEMO</code> <strong>一次性定时器</strong></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #C792EA">let</span><span style="color: #EEFFFF"> timer </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">setTimeout</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">Hello World</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">},</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">3000</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #545454; font-style: italic">// console.log(timer);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #545454; font-style: italic">//clearTimeout(timer) //清除一次性定时器</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="周期性定时器" tabindex="-1"><a class="header-anchor" href="#周期性定时器" aria-hidden="true">#</a> 周期性定时器</h3>
<div class="language-javascript ext-js"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #82AAFF">setInterval</span><span style="color: #EEFFFF">(callback</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF">time</span><span style="color: #89DDFF">,</span><span style="color: #EEFFFF">[</span><span style="color: #89DDFF">...</span><span style="color: #EEFFFF">])</span></span>
<span class="line"></span></code></pre></div><p>计划在xxx毫秒后执行一次回调函数<code v-pre>callback</code>(可重复执行回调),返回一个<code v-pre>intervalObject</code>,供<code v-pre>clearInterval</code>在需要的时候使用<br>
<code v-pre>clearInterval</code>(返回一个intervalObject) 清除周期性定时器</p>
<p><code v-pre>DEMO</code> <strong>周期性定时器</strong></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 如果对定时器不做条件限制,周期性定时器会一直执行下去</span></span>
<span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> count </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #C792EA">let</span><span style="color: #EEFFFF"> timer </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">setInterval</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">Hello World</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">count</span><span style="color: #89DDFF">++;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #F07178"> (</span><span style="color: #EEFFFF">count</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&gt;</span><span style="color: #F07178"> </span><span style="color: #F78C6C">3</span><span style="color: #F07178">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">//clearInterval(timer) //清除周期性定时器</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #82AAFF">clearInterval</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">timer</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #89DDFF">},</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">2000</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="立即执行定时器" tabindex="-1"><a class="header-anchor" href="#立即执行定时器" aria-hidden="true">#</a> 立即执行定时器 <Badge text="了解" /></h3>
<p>立即执行定时器(控制代码执行顺序)</p>
<p><code v-pre>DEMO</code> <strong>立即执行定时器</strong></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// setImmediate 如果你想将一些异步的代码尽早的执行,那么可以使用此函数</span></span>
<span class="line"><span style="color: #82AAFF">setImmediate</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">Hello World</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #545454; font-style: italic">// 立即执行定时器(主要原因是上方的定时器比较拉胯,不太好用,有更加严格的调用规则)</span></span>
<span class="line"><span style="color: #EEFFFF">process</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">nextTick</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">Hello Nodejs</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">}</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="事件循环" tabindex="-1"><a class="header-anchor" href="#事件循环" aria-hidden="true">#</a> 事件循环 <Badge text="理解" /></h3>
<p><img src="@source/.vuepress/public/images/事件循环.png" alt="事件循环"></p>
<p>事件的循环，分为6个阶段，每个阶段都有自己特殊的任务。</p>
<ol>
<li>timers    给定时器制定一个执行的下限时间</li>
<li>系统回调</li>
<li>prepare Node内部回调</li>
<li>poll(事件队列)
<ul>
<li>如果存在setImmediate的设定,则事件循环结束后立即结束poll阶段进入check阶段</li>
<li>如果不存在setImmediate的设定,则会查看是否有其他的定时器setTimeout或者setInterval,如果有有则事件循环绕会timers阶段执行,如果没有则阻塞在poll阶段中,等待回调</li>
</ul>
</li>
<li>check 立即执行setImmediate</li>
<li>close callbakc 正常情况下几乎不会发生</li>
</ol>
<h3 id="倒计时" tabindex="-1"><a class="header-anchor" href="#倒计时" aria-hidden="true">#</a> 倒计时 <Badge text="练习" /></h3>
<div class="custom-container tip"><p class="custom-container-title">利用定时器(周期)完成倒计时功能</p>
<p><strong>倒计时</strong>: 在终端中打印出距离xx天xx时xx分xx秒结束秒杀活动</p>
<p><strong>任务分解</strong>:</p>
<ol>
<li>确定定时器 → 周期。</li>
<li>确定结束时间。</li>
<li>不断的获取当前时间，并计算当前时间距离结束时间的时间差。</li>
<li>如果时间到，清除定时器。</li>
</ol>
</div>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">// 设定结束时间</span></span>
<span class="line"><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> endTime </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">new</span><span style="color: #EEFFFF"> </span><span style="color: #FFCB6B">Date</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">2022/3/28 20:43:00</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #C792EA">let</span><span style="color: #EEFFFF"> timer </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">setInterval</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #C792EA">=&gt;</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 获取当前时间</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #C792EA">var</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">nowTime</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">new</span><span style="color: #F07178"> </span><span style="color: #FFCB6B">Date</span><span style="color: #F07178">()</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 计算剩余时间 得到的是毫秒数, 需要换算秒 方便计算后续内容</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #C792EA">var</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">lastTime</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> (</span><span style="color: #EEFFFF">endTime</span><span style="color: #F07178"> </span><span style="color: #89DDFF">-</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">nowTime</span><span style="color: #F07178">) </span><span style="color: #89DDFF">/</span><span style="color: #F07178"> </span><span style="color: #F78C6C">1000</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 如果lastTime小于0说明已经到时间,清除定时器</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF; font-style: italic">if</span><span style="color: #F07178"> (</span><span style="color: #EEFFFF">lastTime</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&gt;</span><span style="color: #F07178"> </span><span style="color: #F78C6C">0</span><span style="color: #F07178">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 计算天 86400  </span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">day</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #82AAFF">parseInt</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">lastTime</span><span style="color: #F07178"> </span><span style="color: #89DDFF">/</span><span style="color: #F07178"> </span><span style="color: #F78C6C">24</span><span style="color: #F07178"> </span><span style="color: #89DDFF">/</span><span style="color: #F07178"> </span><span style="color: #F78C6C">60</span><span style="color: #F07178"> </span><span style="color: #89DDFF">/</span><span style="color: #F07178"> </span><span style="color: #F78C6C">60</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 计算小时 余数代表小时</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">hour</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #82AAFF">parseInt</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">lastTime</span><span style="color: #F07178"> </span><span style="color: #89DDFF">/</span><span style="color: #F07178"> </span><span style="color: #F78C6C">60</span><span style="color: #F07178"> </span><span style="color: #89DDFF">/</span><span style="color: #F07178"> </span><span style="color: #F78C6C">60</span><span style="color: #F07178"> </span><span style="color: #89DDFF">%</span><span style="color: #F07178"> </span><span style="color: #F78C6C">24</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 计算分钟</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">min</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #82AAFF">parseInt</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">lastTime</span><span style="color: #F07178"> </span><span style="color: #89DDFF">/</span><span style="color: #F07178"> </span><span style="color: #F78C6C">60</span><span style="color: #F07178"> </span><span style="color: #89DDFF">%</span><span style="color: #F07178"> </span><span style="color: #F78C6C">60</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 计算秒</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">sec</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #82AAFF">parseInt</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">lastTime</span><span style="color: #F07178"> </span><span style="color: #89DDFF">%</span><span style="color: #F07178"> </span><span style="color: #F78C6C">60</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// es6的模板化字符串输出</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">距离</span><span style="color: #89DDFF">${</span><span style="color: #EEFFFF">day</span><span style="color: #89DDFF">}</span><span style="color: #C3E88D">天</span><span style="color: #89DDFF">${</span><span style="color: #EEFFFF">hour</span><span style="color: #89DDFF">}</span><span style="color: #C3E88D">时</span><span style="color: #89DDFF">${</span><span style="color: #EEFFFF">min</span><span style="color: #89DDFF">}</span><span style="color: #C3E88D">分</span><span style="color: #89DDFF">${</span><span style="color: #EEFFFF">sec</span><span style="color: #89DDFF">}</span><span style="color: #C3E88D">秒结束秒杀活动</span><span style="color: #89DDFF">`</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span><span style="color: #F07178"> </span><span style="color: #89DDFF; font-style: italic">else</span><span style="color: #F07178"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #82AAFF">clearInterval</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">timer</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span><span style="color: #F07178"> </span></span>
<span class="line"><span style="color: #89DDFF">},</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">1000</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
