<template><div><h1 id="dom" tabindex="-1"><a class="header-anchor" href="#dom" aria-hidden="true">#</a> DOM</h1>
<p>DOM: <strong>D</strong>ocument <strong>O</strong>bject <strong>M</strong>odel 文档对象模型<br>
即把网页当做成对象，把网页中的所有元素标签都当做节点。</p>
<h2 id="简易dom" tabindex="-1"><a class="header-anchor" href="#简易dom" aria-hidden="true">#</a> 简易DOM</h2>
<p>简易DOM事件修改浏览器元素内的流程</p>
<ol>
<li>由元素触发单击事件 onclick</li>
<li>获取元素DOM对象：
<ul>
<li>之前常用方式: document.getElementById(id值)</li>
<li>现在推荐方式: id值.方法 如: d1.innerHTML</li>
</ul>
</li>
<li>使用innerHTML 或者 value 方式获取DOM对象中的值</li>
<li>重新赋值来达到修改内容的目的</li>
</ol>
<h3 id="改值" tabindex="-1"><a class="header-anchor" href="#改值" aria-hidden="true">#</a> 改值</h3>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">div</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">id</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">d1</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;</span><span style="color: #EEFFFF">A</span><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">div</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #545454; font-style: italic">&lt;!-- onclick js中的单击事件 --&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">button</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">onclick</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #82AAFF">setName</span><span style="color: #C3E88D">()</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;</span><span style="color: #EEFFFF">修改A为B</span><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">button</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 获取div对象</span></span>
<span class="line"><span style="color: #89DDFF">    </span><span style="color: #545454; font-style: italic">// 获取指定ID值的一个DOM对象</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #C792EA">var</span><span style="color: #EEFFFF"> divEle </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> document</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">getElementById</span><span style="color: #EEFFFF">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">d1</span><span style="color: #89DDFF">&#39;</span><span style="color: #EEFFFF">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #EEFFFF">    console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #EEFFFF">(divEle)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #C792EA">function</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">setName</span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 获取数据</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// innerHTML 可以用来获取或者设置标签中的元素</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">data</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">divEle</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">innerHTML</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">data</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 修改数据</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">divEle</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">innerHTML</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">B</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 思考3个问题: </span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 1. divEle对象是什么样的? </span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">//    整个div的dom节点</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 2. 获取的数据时是什么?</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">//    标签中的值</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 3. 修改数据的原理是是什么?</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">//    重复赋值</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span><span style="color: #EEFFFF">      </span></span>
<span class="line"><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="改值并储存" tabindex="-1"><a class="header-anchor" href="#改值并储存" aria-hidden="true">#</a> 改值并储存</h3>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #545454; font-style: italic">&lt;!-- 点击按钮把A变成B --&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">input</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">type</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">text</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">value</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">1</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">id</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">in1</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">button</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">onclick</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #82AAFF">setName</span><span style="color: #C3E88D">()</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;</span><span style="color: #EEFFFF">改值</span><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">button</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #C792EA">function</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">setName</span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 获取input对象</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #C792EA">var</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">intEle</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">document</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">getElementById</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">in1</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #EEFFFF">intEle</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 获取对象中的数据并设置值</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">intEle</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">value</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">B</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #545454; font-style: italic">&lt;!-- 点击按钮把小艺放在div中 --&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">br</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">button</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">onclick</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #82AAFF">setValue</span><span style="color: #C3E88D">()</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;</span><span style="color: #EEFFFF">点我存值</span><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">button</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">div</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">id</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">d1</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;&lt;/</span><span style="color: #F07178">div</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #C792EA">function</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">setValue</span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 获取div对象修改至 简化写法</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">d1</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">innerHTML</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">B</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="输出html标签" tabindex="-1"><a class="header-anchor" href="#输出html标签" aria-hidden="true">#</a> 输出html标签</h3>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">button</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">onclick</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #82AAFF">add</span><span style="color: #C3E88D">()</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;</span><span style="color: #EEFFFF">增加超链接</span><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">button</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">div</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">id</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">d1</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;&lt;/</span><span style="color: #F07178">div</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #C792EA">function</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">add</span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">被触发了</span><span style="color: #89DDFF">&quot;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">d1</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">innerHTML</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">&lt;a href=&quot;&quot;&gt;百度&lt;/a&gt;</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="取值拼接" tabindex="-1"><a class="header-anchor" href="#取值拼接" aria-hidden="true">#</a> 取值拼接</h3>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">input</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">type</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">text</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">placeholder</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">请输入值</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">id</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">int1</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">div</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">id</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">d1</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;&lt;/</span><span style="color: #F07178">div</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">button</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">onclick</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #82AAFF">addValue</span><span style="color: #C3E88D">()</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;</span><span style="color: #EEFFFF">点我把input里的值添加到div中变成列表</span><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">button</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #C792EA">function</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">addValue</span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">触发事件</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// // 1. 获取input的值</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// let intEle = document.getElementById(&#39;int1&#39;).value;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// console.log(&#39;获取input的值&#39;,intEle);</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// // 2. 获取div对象</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// let divEle = document.getElementById(&#39;d1&#39;);</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// // 3. 赋值</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// divEle.innerHTML = `</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">//             &lt;ul&gt;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">//                 &lt;li&gt;${intEle}&lt;/li&gt;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">//             &lt;/ul&gt;`;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">//    上方写法简化</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">d1</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">innerHTML</span><span style="color: #F07178"> </span><span style="color: #89DDFF">+=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">&lt;ul&gt;&lt;li&gt;</span><span style="color: #89DDFF">${</span><span style="color: #EEFFFF">int1</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">value</span><span style="color: #89DDFF">}</span><span style="color: #C3E88D">&lt;/li&gt;&lt;/ul&gt;</span><span style="color: #89DDFF">`</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查询拼接1" tabindex="-1"><a class="header-anchor" href="#查询拼接1" aria-hidden="true">#</a> 查询拼接1</h3>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">button</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">onclick</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #82AAFF">show</span><span style="color: #C3E88D">()</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;</span><span style="color: #EEFFFF">点我展示表格数据</span><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">button</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">div</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">id</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">d1</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;&lt;/</span><span style="color: #F07178">div</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #EEFFFF">    </span></span>
<span class="line"><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #C792EA">let</span><span style="color: #EEFFFF"> arr </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> [</span></span>
<span class="line"><span style="color: #EEFFFF">        </span><span style="color: #89DDFF">{</span><span style="color: #F07178">id</span><span style="color: #89DDFF">:</span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">,</span><span style="color: #F07178">name</span><span style="color: #89DDFF">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">小艺</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #F07178">age</span><span style="color: #89DDFF">:</span><span style="color: #F78C6C">18</span><span style="color: #89DDFF">},</span></span>
<span class="line"><span style="color: #EEFFFF">        </span><span style="color: #89DDFF">{</span><span style="color: #F07178">id</span><span style="color: #89DDFF">:</span><span style="color: #F78C6C">2</span><span style="color: #89DDFF">,</span><span style="color: #F07178">name</span><span style="color: #89DDFF">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">小宇</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #F07178">age</span><span style="color: #89DDFF">:</span><span style="color: #F78C6C">19</span><span style="color: #89DDFF">},</span></span>
<span class="line"><span style="color: #EEFFFF">        </span><span style="color: #89DDFF">{</span><span style="color: #F07178">id</span><span style="color: #89DDFF">:</span><span style="color: #F78C6C">3</span><span style="color: #89DDFF">,</span><span style="color: #F07178">name</span><span style="color: #89DDFF">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">申哥</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #F07178">age</span><span style="color: #89DDFF">:</span><span style="color: #F78C6C">20</span><span style="color: #89DDFF">},</span></span>
<span class="line"><span style="color: #EEFFFF">    ]</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #C792EA">function</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">show</span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">触发了</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 表格上半部分</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">str</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">`</span></span>
<span class="line"><span style="color: #C3E88D">                &lt;table border=&quot;1&quot; bordercolor=&quot;red&quot;&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                    &lt;tr&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                        &lt;td&gt;编号&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                        &lt;td&gt;姓名&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                        &lt;td&gt;年龄&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                    &lt;/tr&gt;</span><span style="color: #89DDFF">`</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 数据</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #F07178"> (</span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">i</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #F78C6C">0</span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">i</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&lt;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">arr</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">length</span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">i</span><span style="color: #89DDFF">++</span><span style="color: #F07178">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #EEFFFF">str</span><span style="color: #F07178"> </span><span style="color: #89DDFF">+=</span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">&lt;tr&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                        &lt;td&gt;</span><span style="color: #89DDFF">${</span><span style="color: #EEFFFF">arr[i]</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">id</span><span style="color: #89DDFF">}</span><span style="color: #C3E88D">&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                        &lt;td&gt;</span><span style="color: #89DDFF">${</span><span style="color: #EEFFFF">arr[i]</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">name</span><span style="color: #89DDFF">}</span><span style="color: #C3E88D">&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                        &lt;td&gt;</span><span style="color: #89DDFF">${</span><span style="color: #EEFFFF">arr[i]</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">age</span><span style="color: #89DDFF">}</span><span style="color: #C3E88D">&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                    &lt;/tr&gt;</span><span style="color: #89DDFF">`</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF">}</span><span style="color: #F07178">           </span></span>
<span class="line"><span style="color: #F07178">                    </span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// 下半部分</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">str</span><span style="color: #F07178"> </span><span style="color: #89DDFF">+=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">&lt;/table&gt;</span><span style="color: #89DDFF">`</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #EEFFFF">d1</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">innerHTML</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">str</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">    </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查询拼接2" tabindex="-1"><a class="header-anchor" href="#查询拼接2" aria-hidden="true">#</a> 查询拼接2</h3>
<p>通过js进行判断</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="shiki" style="background-color: #212121"><code><span class="line"><span style="color: #EEFFFF">    </span><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">button</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">onclick</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #82AAFF">show</span><span style="color: #C3E88D">()</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;</span><span style="color: #EEFFFF">点我展示表格数据</span><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">button</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #89DDFF">&lt;</span><span style="color: #F07178">div</span><span style="color: #89DDFF"> </span><span style="color: #C792EA">id</span><span style="color: #89DDFF">=</span><span style="color: #89DDFF">&quot;</span><span style="color: #C3E88D">d1</span><span style="color: #89DDFF">&quot;</span><span style="color: #89DDFF">&gt;&lt;/</span><span style="color: #F07178">div</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF">    &lt;</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"><span style="color: #89DDFF">        </span><span style="color: #545454; font-style: italic">// sex: 0代表男 1代表女</span></span>
<span class="line"><span style="color: #EEFFFF">        </span><span style="color: #C792EA">let</span><span style="color: #EEFFFF"> arr </span><span style="color: #89DDFF">=</span><span style="color: #EEFFFF"> [</span></span>
<span class="line"><span style="color: #EEFFFF">            </span><span style="color: #89DDFF">{</span><span style="color: #F07178">id</span><span style="color: #89DDFF">:</span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">,</span><span style="color: #F07178">name</span><span style="color: #89DDFF">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">小艺</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #F07178">sex</span><span style="color: #89DDFF">:</span><span style="color: #F78C6C">1</span><span style="color: #89DDFF">},</span></span>
<span class="line"><span style="color: #EEFFFF">            </span><span style="color: #89DDFF">{</span><span style="color: #F07178">id</span><span style="color: #89DDFF">:</span><span style="color: #F78C6C">2</span><span style="color: #89DDFF">,</span><span style="color: #F07178">name</span><span style="color: #89DDFF">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">小宇</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #F07178">sex</span><span style="color: #89DDFF">:</span><span style="color: #F78C6C">0</span><span style="color: #89DDFF">},</span></span>
<span class="line"><span style="color: #EEFFFF">            </span><span style="color: #89DDFF">{</span><span style="color: #F07178">id</span><span style="color: #89DDFF">:</span><span style="color: #F78C6C">3</span><span style="color: #89DDFF">,</span><span style="color: #F07178">name</span><span style="color: #89DDFF">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">申哥</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">,</span><span style="color: #F07178">sex</span><span style="color: #89DDFF">:</span><span style="color: #F78C6C">0</span><span style="color: #89DDFF">},</span></span>
<span class="line"><span style="color: #EEFFFF">        ]</span></span>
<span class="line"></span>
<span class="line"><span style="color: #EEFFFF">        </span><span style="color: #C792EA">function</span><span style="color: #EEFFFF"> </span><span style="color: #82AAFF">show</span><span style="color: #89DDFF">()</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #EEFFFF">console</span><span style="color: #89DDFF">.</span><span style="color: #82AAFF">log</span><span style="color: #F07178">(</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">触发了</span><span style="color: #89DDFF">&#39;</span><span style="color: #F07178">)</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">            </span><span style="color: #545454; font-style: italic">// 表格上半部分  </span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">str</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">`</span></span>
<span class="line"><span style="color: #C3E88D">                    &lt;table border=&quot;1&quot; bordercolor=&quot;pink&quot;&gt; </span></span>
<span class="line"><span style="color: #C3E88D">                        &lt;tr&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                            &lt;td&gt;编号&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                            &lt;td&gt;姓名&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                            &lt;td&gt;性别&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                            &lt;td&gt;操作&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                        &lt;/tr&gt;</span><span style="color: #89DDFF">`</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #89DDFF">            </span><span style="color: #545454; font-style: italic">// 数据</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #89DDFF; font-style: italic">for</span><span style="color: #F07178"> (</span><span style="color: #C792EA">let</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">i</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #F78C6C">0</span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">i</span><span style="color: #F07178"> </span><span style="color: #89DDFF">&lt;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">arr</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">length</span><span style="color: #89DDFF">;</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">i</span><span style="color: #89DDFF">++</span><span style="color: #F07178">) </span><span style="color: #89DDFF">{</span></span>
<span class="line"><span style="color: #F07178">                </span><span style="color: #EEFFFF">str</span><span style="color: #F07178"> </span><span style="color: #89DDFF">+=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">&lt;tr&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                            &lt;td&gt;</span><span style="color: #89DDFF">${</span><span style="color: #EEFFFF">arr[i]</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">id</span><span style="color: #89DDFF">}</span><span style="color: #C3E88D">&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                            &lt;td&gt;</span><span style="color: #89DDFF">${</span><span style="color: #EEFFFF">arr[i]</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">name</span><span style="color: #89DDFF">}</span><span style="color: #C3E88D">&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                            &lt;td&gt;</span><span style="color: #89DDFF">${</span><span style="color: #EEFFFF">arr[i]</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">sex </span><span style="color: #89DDFF">==</span><span style="color: #EEFFFF"> </span><span style="color: #F78C6C">0</span><span style="color: #EEFFFF"> </span><span style="color: #89DDFF">?</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">男</span><span style="color: #89DDFF">&#39;</span><span style="color: #89DDFF">:</span><span style="color: #89DDFF">&#39;</span><span style="color: #C3E88D">女</span><span style="color: #89DDFF">&#39;}</span><span style="color: #C3E88D">&lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                            &lt;td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                                &lt;a href=&quot;&quot;&gt;查看&lt;/a&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                                &lt;a href=&quot;&quot;&gt;删除&lt;/a&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                                &lt;a href=&quot;&quot;&gt;修改&lt;/a&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                            &lt;/td&gt;</span></span>
<span class="line"><span style="color: #C3E88D">                        &lt;/tr&gt;</span><span style="color: #89DDFF">`</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #89DDFF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #89DDFF">            </span><span style="color: #545454; font-style: italic">// 下半部分</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #EEFFFF">str</span><span style="color: #F07178"> </span><span style="color: #89DDFF">+=</span><span style="color: #F07178"> </span><span style="color: #89DDFF">`</span><span style="color: #C3E88D">&lt;/table&gt;</span><span style="color: #89DDFF">`</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">            </span><span style="color: #EEFFFF">d1</span><span style="color: #89DDFF">.</span><span style="color: #EEFFFF">innerHTML</span><span style="color: #F07178"> </span><span style="color: #89DDFF">=</span><span style="color: #F07178"> </span><span style="color: #EEFFFF">str</span><span style="color: #89DDFF">;</span></span>
<span class="line"><span style="color: #F07178">        </span><span style="color: #89DDFF">}</span></span>
<span class="line"><span style="color: #EEFFFF">    </span><span style="color: #89DDFF">&lt;/</span><span style="color: #F07178">script</span><span style="color: #89DDFF">&gt;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
